# Generated by Django 5.1.4 on 2026-09-06 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=600)),
                ('normalized_url', models.CharField(blank=True, db_index=True, max_length=600)),
                ('category', models.CharField(choices=[('MSc', 'MSc / Masters'), ('PhD', 'PhD'), ('Quant Role', 'Quant Role'), ('SWE Role', 'Software / Tech Role'), ('Hackathon', 'Hackathon'), ('Fellowship', 'Fellowship'), ('Scholarship', 'Scholarship'), ('Other', 'Other')], default='Other', max_length=30)),
                ('funding_status', models.CharField(choices=[('Fully Funded', 'Fully Funded'), ('Partial', 'Partially Funded'), ('Cash Prize', 'Cash Prize'), ('Paid Role', 'Paid Role'), ('Unfunded', 'Unfunded / Unknown')], default='Unfunded', max_length=30)),
                ('summary', models.TextField(blank=True)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['deadline', '-date_scraped'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='scout_oppor_categor_413d97_idx'), models.Index(fields=['deadline', 'is_active'], name='scout_oppor_deadlin_097e32_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_url',), name='unique_normalized_url')],
            },
        ),
        migrations.CreateModel(
            name='UserProfilePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('preferred_regions', models.CharField(blank=True, help_text='Comma-separated regions of interest, e.g. Europe, UK, Canada, Remote', max_length=300)),
                ('keywords', models.CharField(blank=True, help_text='Extra keywords to prioritize, e.g. quant, fintech, machine learning', max_length=300)),
                ('email_digest_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scout_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'New'), ('Interested', 'Interested'), ('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='New', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='scout.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_user_saved_opportunity')],
            },
        ),
    ]
